from .main_settings import DB_NAME
from .main_settings import KEY
from .main_settings import PERCENTAGE_COMMISSION
from .main_settings import PERCENTAGE_DOWN_TO
from .main_settings import PERCENTAGE_RISE_UP_TO
from .main_settings import PERCENTAGE_STOP_LOSS
from .main_settings import PERCENTAGE_TRIGGER_PRICE_FALL_PER_MINUTE
from .main_settings import PERCENTAGE_TRIGGER_PRICE_FALL_PER_MINUTE_FOR_BUY
from .main_settings import PERCENTAGE_WAIT_AFTER_SELL
from .main_settings import PERCENTAGE_WAIT_FOR_BUY
from .main_settings import ROUNDING
from .main_settings import SECRET
from .main_settings import TOKEN
from .main_settings import TIME_FORMAT

from .const import COEFFICIENT_DOWN_TO
from .const import COEFFICIENT_FOR_PROFIT
from .const import COEFFICIENT_RISE_UP_TO
from .const import COEFFICIENT_WAIT_AFTER_SELL
from .const import COEFFICIENT_WAIT_FOR_BUY
from .const import TRIGGER_PRICE_FALL_PER_MINUTE
from .const import TRIGGER_PRICE_FALL_PER_MINUTE_FOR_BUY
from .const import ONLINE_TRADE
from .const import STOP_LOSS_RATIO
